server:
  port: 8080
    
spring:
  application:
  name: "heroes-challenge"
  mvc:
    pathmatch:
      matching-strategy: "ant-path-matcher"
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:heroes;MODE=MySQL
    platform: h2

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

jwt:
  secret: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
  validaty: 18000
