version: '3'
 
services:
  heroes-challenge-app:
    image: heroes-challenge-app:latest
    container_name: heroes_challenge_container
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ../config:/app/config